-- Insert 20 new generated words (batch 5)

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Fermentum', 'Fermentum means anything that causes fermentation, generally referred to as yeast or a leavening agent.', 'fer-MEN-tum', 'From the Latin ''fervere'', meaning ''to boil''.', 'The fermentum added to the dough caused it to rise beautifully.', 'Fermentum ad massam additum eam pulchre crescere fecit.', 'Chefs insist that the right fermentum is crucial for making the perfect sourdough.', 'Coci affirmant rectum fermentum esse crucialem ad perfectum panem acorem faciendum.', 'In ancient times, fermentum was a vital element in food preservation.', 'Antiquis temporibus, fermentum erat elementum vitale in cibo conservando.', '{zymum,levar}', '{}', 'fermentum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Fermentum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Follium', 'Follium means leaf in Latin, often used in reference to foliage or pages of a book.', 'FOL-lee-um', 'Derived from the Latin ''folium'', meaning ''leaf''.', 'The autumn wind rustled the follium as they danced to the ground.', 'Ventus autumnalis follium commovit dum ad terram saltarent.', 'Turning the follium of the manuscript, she discovered ancient secrets.', 'Follium manuscripti vertens, antiqua secreta invenit.', 'The artist''s canvas was surrounded by a cascade of colorful follium.', 'Tabula artificis circumdata erat casu coloratorum foliorum.', '{pagina,frons}', '{}', 'follium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Follium'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Hostia', 'Hostia means sacrificial victim or offering, often used in religious contexts.', 'HOS-tee-ah', 'Relates to the Latin ''hostis'', meaning ''enemy'', referring to an offering of appeasement.', 'In ancient rituals, a hostia was offered to the gods to seek their favor.', 'In antiquis ritibus, hostia diis oblata est ut favorem eorum peteret.', 'The priest blessed the hostia before the congregation.', 'Sacerdos hostiam ante congregationem benedixit.', 'A hostia was traditionally burned on the altar as part of the ceremony.', 'Hostia tradito in altari comburebatur ut pars caerimoniae.', '{sacrificium,oblatio}', '{}', 'hostia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Hostia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Opalus', 'Opalus means an opal, a precious gemstone known for its shimmering colors.', 'OH-pah-lus', 'From the Greek ''opallios'', meaning ''to see a change in color''.', 'The opalus in her ring reflected the light in a spectrum of colors.', 'Opalus in anulo eius lucem in spectrum colorum reflectebat.', 'Ancient Romans believed that an opalus granted the owner prophecy abilities.', 'Antiqui Romani credebant opalum domino facultates prophetiae dare.', 'The crown was adorned with a stunning opalus, set among other jewels.', 'Corona ornata erat opalo mirabili, inter alias gemmas posito.', '{gemma,lapis}', '{}', 'opalus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Opalus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Sapidus', 'Sapidus means savory or tasty, used to describe delicious flavors.', 'SAH-pi-dus', 'Derived from the Latin ''sapere'', meaning ''to taste''.', 'The chef prepared a sapidus feast that tantalized everyone''s taste buds.', 'Cocus sapidum epulum paravit quod omnium gustus irritavit.', 'Each bite of the sapidus dish left them wanting more.', 'Quisque morsus sapidi ferculi eos plus cupere reliquit.', 'She had a knack for cooking sapidus meals with simple ingredients.', 'Artem habebat coquendi sapida fercula cum simplicibus ingredientibus.', '{gustosus,esculentus}', '{}', 'sapidus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Sapidus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Substantia', 'Substantia means substance or essence, often referring to the fundamental nature of something.', 'sub-STAN-ti-ah', 'From the Latin ''substantia'', meaning ''essence'' or ''material''.', 'The scientist studied the substantia of the newly discovered element.', 'Cercetator substantiam novi elementi investigavit.', 'She admired the substantia of the painting, noticing its depth and meaning.', 'Substantiam picturae admirata est, eius profunditatem et significationem notans.', 'In philosophy, questions of substantia address the nature of reality itself.', 'In philosophia, quaestiones substantiae naturam ipsius realitatis tractant.', '{essentia,materia}', '{}', 'substantia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Substantia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Tenebra', 'Tenebra means darkness or shadow, often used to symbolize ignorance or evil.', 'TEN-eh-brah', 'Stems from the Latin ''tenebrae'', meaning ''darkness''.', 'The tenebra of the cave was foreboding, challenging the bravest explorers.', 'Tenebra speluncae formidabilis erat, fortissimos exploratores provocans.', 'She dispelled the tenebra of ignorance with knowledge and education.', 'Tenebras ignorantiae cum scientia et educatione dissipavit.', 'The villain emerged from the tenebra, plotting his next move.', 'Scelestus e tenebris emersit, proximum consilium machinans.', '{obscuritas,umbra}', '{}', 'tenebra.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Tenebra'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Velum', 'Velum means sail or covering, often referring to a sheet used in sailing or as a curtain.', 'VAY-lum', 'Derived from the Latin word ''velare'', meaning ''to cover''.', 'The bravest sailors adjusted the velum to catch the favorable winds.', 'Fortissimi nautae velum ad ventos secundos capiendos aptaverunt.', 'In the theater, the velum was raised to signal the start of the play.', 'In theatro, velum elevatum est ut initium fabulae significaret.', 'She used a velum to shield the garden from intense sunlight.', 'Velum usus est ut hortum a sole intenso protegeret.', '{vela,velamen}', '{}', 'velum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Velum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Zephyros', 'Zephyros means west wind, gentle and mild, often associated with spring in mythology.', 'ZEH-fi-ros', 'From the Greek ''Zephyros'', the god of the west wind in mythology.', 'The zephyros brought a refreshing breeze that signaled the end of winter.', 'Zephyros attulit auram reficientem quae finem hiemis significavit.', 'She felt the calming touch of the zephyros on her face as she walked.', 'Sentit lenem tactum zephyri in facie dum ambulat.', 'The sails filled with the soft push of the zephyros as they set out to sea.', 'Vela impleta sunt molli impulsu zephyri dum ad mare proficiscuntur.', '{favonius,ventus occidentalis}', '{}', 'zephyros.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Zephyros'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Frater', 'Frater means brother in Latin, often used to denote a male sibling or a close male friend who shares a brotherly bond.', 'FRAH-ter', 'From Proto-Indo-European *bʰréh₂tēr, related to English brother.', 'He treated his childhood friend like a true frater.', 'Amicum pueritiae sicut verum fratrem tractavit.', 'The bond between them was as strong as that of frater.', 'Vinculum inter eos tam forte erat quam fratris.', 'In times of need, a frater is always there to support you.', 'In necessitatibus, frater semper adest ut te sustineat.', '{Germānus,Consobrinus}', '{}', 'frater.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Frater'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Notitia', 'Notitia means knowledge or acquaintance, referring to the state of being informed or aware about something.', 'no-TI-tee-ah', 'From the Latin notus, meaning known.', 'Her notitia of ancient history was impressive.', 'Eius notitia historiae antiquae erat mirabilis.', 'You need to have notitia about local customs before traveling.', 'Oportet habere notitiam de moribus localibus antequam iter facias.', 'With notitia comes the power to make informed decisions.', 'Cum notitia venit potestas ad decisiones informatas faciendas.', '{Scientia,Cognitio}', '{}', 'notitia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Notitia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Pastor', 'Pastor means shepherd, someone who tends and watches over a flock of sheep.', 'PAHS-tor', 'From Proto-Indo-European *peh₂-, meaning to protect or guard.', 'The pastor led his flock across the meadow.', 'Pastor gregem suum per pratum duxit.', 'As a wise pastor, he knew each sheep by name.', 'Ut sapiens pastor, novit singulas oves nomine.', 'Under the stars, the pastor kept watch through the night.', 'Sub stellis, pastor per noctem vigilavit.', '{Custos,Agitator}', '{}', 'pastor.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Pastor'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Serpens', 'Serpens means ''snake'' or ''serpent'' in Latin, referring to a limbless, elongated reptile that often elicits fear or fascination.', '/ˈsɛr.pens/', 'Derived from the Latin verb ''serpere,'' meaning ''to creep'' or ''crawl.''', 'In ancient mythology, the serpens was often associated with healing and transformation.', 'In mythologia antiqua, serpens saepe cum sanatione et transformatione coniunctus est.', 'The garden was home to a serpens that slithered silently among the flowers.', 'Hortus erat domus serpentis qui silentio inter flores serpebat.', 'The symbol of the serpens on the caduceus is a mark of medical profession.', 'Symbolum serpentis in caduceo est signum professionis medicae.', '{Anguis,Vermis}', '{}', 'serpens.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Serpens'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Rupes', 'Rupes means ''cliff'' or ''rock'' in Latin, describing a steep face of rock or a precipice.', '/ˈruː.pes/', 'Derived from the Latin verb ''rumpere,'' meaning ''to break'' or ''to burst.''', 'The daredevils stood at the edge of the rupes, peering down at the ocean below.', 'Audaces steterunt in margine rupis, spectantes ad oceanum infra.', 'Wind and water have carved the rupes over centuries.', 'Ventus et aqua rupem per saecula sculpsit.', 'The view from the rupes was breathtaking, offering a panorama of the valley.', 'Visus ex rupe erat mirabilis, offerens panoramam vallis.', '{Saxum,Praeruptum}', '{}', 'rupes.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Rupes'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Mutatio', 'Mutatio means ''change'' or ''alteration'' in Latin, signifying a process of transformation or conversion.', '/muˈtaː.ti.oː/', 'From the Latin verb ''mutare,'' meaning ''to change'' or ''to move.''', 'The mutatio of seasons is a natural cycle observed by all.', 'Mutatio temporum est naturalis cyclus ab omnibus observatus.', 'In history, mutatio in leadership often leads to shifts in policy.', 'In historia, mutatio in ducatu saepe ad mutationes in consilio ducit.', 'The scientific community embraces mutatio as a crucial factor of innovation.', 'Communitas scientifica mutationem amplectitur ut factor innovationis crucialis.', '{Vicissitudo,Transmutatio}', '{}', 'mutatio.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Mutatio'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Salus', 'Salus means ''health'' or ''welfare'' in Latin, referring to the state of being free from illness or injury.', '/ˈsaː.lus/', 'Comes from the Latin root ''salvus,'' meaning ''safe'' or ''healthy.''', 'Public salus was prioritized in the new health policies introduced by the government.', 'Publica salus in novis legibus sanitatis a gubernatione introductis prioritas fuit.', 'Ancient Romans often invoked deities for protection and salus.', 'Romani antiqui saepe deos invocabant pro tutela et salute.', 'Good nutrition plays a critical role in maintaining salus.', 'Bona nutritio partes criticas agit in salute conservanda.', '{Sanitas,Benevolentia}', '{}', 'salus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Salus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Apex', 'Apex means ''peak'' or ''summit'' in Latin, referring to the highest point or the culmination of something.', '/ˈa.peks/', 'From the Latin root ''apex,'' meaning ''summit'' or ''vertex.''', 'The climbers reached the apex of the mountain after a grueling ascent.', 'Scalatores apicem montis post arduam ascensionem attigerunt.', 'In the apex of her career, she was celebrated worldwide for her achievements.', 'In apice suae vitae, celebrabatur per orbem terrarum ob res gestas.', 'The apex of the pyramid was bathed in golden sunlight.', 'Apex pyramidis aureo sole perfusus est.', '{Summum,Vertex}', '{}', 'apex.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Apex'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Libellula', 'Libellula means a dragonfly, an insect known for its agile flight and often vibrant coloration.', 'li-BEL-lu-la', 'From Latin ''libella'', meaning ''little book'', due to the wing''s shape resembling an open book.', 'The libellula darted across the pond, its wings shimmering in the sunlight.', 'Libellula trans stagnum volavit, alis in sole coruscantibus.', 'Children in the park chased the libellula, fascinated by its rapid movements.', 'Pueri in horto libellulam persequebantur, motibus rapidis fascinati.', 'A libellula landed gently on a reed, resting its gossamer wings.', 'Libellula leniter in arundine consedit, alas suas tenues requiescens.', '{Odonata,Anisoptera}', '{}', 'libellula.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Libellula'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Saxum', 'Saxum means a rock or stone, a solid mineral formation often composing the Earth''s crust.', 'SAK-sum', 'Stemming from the Proto-Indo-European root ''sekh'', meaning ''to cut or split''.', 'The ancient castle was built on a towering saxum, giving it a strategic advantage.', 'Castrum antiquum in saxum excelsum aedificatum est, quod ei commodum strategicum dabat.', 'Climbers sought the challenge of scaling the sheer face of the saxum.', 'Ascensores provocationem petebant ad faciem saxum arduam scandendam.', 'The path was scattered with loose saxa, making the hike treacherous.', 'Iter saxis solutis sparsum erat, quod iter periculosum faciebat.', '{Lapis,Rupes}', '{}', 'saxum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Saxum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Cognitio', 'Cognitio means the process of acquiring knowledge and understanding through thought, experience, and the senses.', 'kohg-NEE-tee-oh', 'Derived from the Latin verb ''cognoscere'', meaning ''to know'' or ''to learn''.', 'His cognitio of ancient history was evident in his detailed research papers.', 'Eius cognitio historiae antiquae in scriptis suis accuratis manifesta erat.', 'The neuroscientist focused her studies on human cognitio to better understand how we learn.', 'Neuroscientista studia sua in cognitione humana intendit ut melius intellegeret quomodo discamus.', 'A strong foundation in cognitio is essential for developing critical thinking skills.', 'Firma cognitio fundamentum est ad artes criticas cogitandi evolvendas.', '{Scientia,Intellectus}', '{}', 'cognitio.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Cognitio'));
