-- Insert 10 new generated words (batch 6)

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Ignominia', 'Ignominia means disgrace or public shame in a social context, often resulting from dishonorable actions.', 'ig-no-MIN-ee-ah', 'From Latin ''ignominia'', derived from ''in-'' (not) + ''nomen'' (name).', 'The scandal brought immense ignominia to the politician, leading to his resignation.', 'Scandalum immensam ignominiam politico attulit, ad eius renuntiationem ducens.', 'After the betrayal, she lived in ignominia, shunned by her former friends.', 'Post proditionem, in ignominia vixit, a prioribus amicis devitata.', 'Fleeing from battle left the soldier in ignominia, tarnishing his family name.', 'E fuga pugnae miles in ignominia relictus est, nomen familiae maculans.', '{dedecus,infamia}', '{gloria,honor}', 'ignominia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Ignominia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Vis', 'Vis means force, power, or strength, often referring to physical or natural power.', 'wees', 'From Latin ''vis'', related to ''vires'' (strength).', 'The hurricane unleashed its vis upon the coastal towns, causing widespread devastation.', 'Procella suam vim in oppida maritima effudit, vastationem late spargens.', 'The leader''s vis in negotiations was unmatched, securing peace for his country.', 'Dux in negotiationibus vis inimitabilis erat, pacem patriae suae assecurans.', 'She applied her full vis to open the jammed door.', 'Omnem vim suam ad ostium obstructum aperiendum adhibuit.', '{potentia,robur}', '{infirmitas}', 'vis.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Vis'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Luxus', 'Luxus means luxury or excess, typically referring to opulence and overindulgence.', 'LUK-sus', 'From Latin ''luxus'', related to ''luxuria'' (extravagance).', 'The mansion was a testament to his love for luxus, with its gilded interiors and priceless art.', 'Villa erat testimonium amoris eius ad luxum, cum interioribus aureis et arte pretiosa.', 'Her lifestyle of luxus was the envy of all her peers.', 'Eius vita luxus invidia omnium aequalium erat.', 'Critics often argue that such displays of luxus are ultimately unsustainable.', 'Critici saepe contendunt tales luxus ostentationes in fine non sustineri posse.', '{opulentia,delicia}', '{paupertas,modestia}', 'luxus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Luxus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Odor', 'Odor means a smell or scent, which can be pleasant or unpleasant.', 'OH-dor', 'From Latin ''odor'', similar to Proto-Indo-European ''hed-'' (to smell).', 'The kitchen was filled with the rich odor of freshly baked bread.', 'Culina repleta erat divite odore panis nuper cocti.', 'A strange odor wafted through the garden as the mysterious plant bloomed.', 'Odor alienus per hortum flatus est cum planta mysteriosa floruit.', 'The odor of fresh paint lingered in the newly renovated room.', 'Odor recentis picturae in renovata camera mansit.', '{fragrantia,aroma}', '{}', 'odor.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Odor'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Solacium', 'Solacium means comfort or consolation offered in times of distress.', 'soˈla.ki.um', 'Comes from the Latin verb ''solor'', which means to comfort or console.', 'She sought solacium in music after the difficult news.', 'Solacium in musica quaesivit post nuntium difficile.', 'His kind words served as solacium to those grieving.', 'Verba eius benigna solacium dolentibus praebuerunt.', 'They found solacium in each other''s company during hard times.', 'Solacium in mutua societate invenerunt temporibus duris.', '{Consolatio,Levamen}', '{}', 'solacium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Solacium'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Inventio', 'Inventio means ''discovery'' or ''invention'' in Latin, referring to the act of finding or creating something new that did not previously exist.', 'in-ven-TEE-oh', 'Derived from the Latin verb ''invenire'', meaning ''to find.''', 'The inventio of the printing press revolutionized the dissemination of knowledge.', 'Inventio preli typographici disseminationem scientiae revolvit.', 'Her inventio of a new recipe for gluten-free bread quickly gained popularity.', 'Eius inventio novi recepti panis sine glutine cito favorem adeptus est.', 'The scientific community celebrated the inventio of a new sustainable energy source.', 'Communitas scientifica inventionem novi fontis energiae sustinendae celebravit.', '{Reperio,Invenire}', '{}', 'inventio.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Inventio'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Umbilicus', 'Umbilicus means ''navel'' or ''center'' in Latin, often used metaphorically to refer to the central point of something.', 'um-BIL-i-kus', 'From the Latin word ''umbilicus'', meaning ''navel'' or ''central point.''', 'The ancient city was often considered the umbilicus of the empire.', 'Urbs antiqua saepe umbilicus imperii habebatur.', 'In many cultures, the umbilicus is a symbol of life and connection.', 'In multis culturis, umbilicus est symbolum vitae et connexionis.', 'The fountain in the town square serves as the umbilicus of community gatherings.', 'Fons in foro communi umbilicus conventuum communitatis servit.', '{Centrum,Medio}', '{}', 'umbilicus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Umbilicus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Miseria', 'Miseria means misery, referring to a state of suffering or distress.', 'miˈseː.ri.a', 'From Latin ''miser'', meaning wretched or unfortunate.', 'He was trapped in a cycle of miseria.', 'In circulo miseriae captus erat.', 'The novel depicts the miseria of the peasantry.', 'Novella miseriam rusticorum depingit.', 'Despite his wealth, he could not escape his inner miseria.', 'Dives quamvis, miseria sua interna effugere non poterat.', '{Tristitia,Dolor}', '{Felicitas,Laetitia}', 'miseria.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Miseria'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Honor', 'Honor means a sense of ethical conduct or duty, often related to reputation or dignity.', 'ˈho.nor', 'From Latin ''honor'', related to esteem and reverence.', 'He fought to restore his family''s honor.', 'Pugnavit ut honorem familiae suae restitueret.', 'Honor was at the heart of their code of conduct.', 'Honor in corde eorum morum codice erat.', 'The medal was a symbol of his honor.', 'Medalia erat symbolum honoris eius.', '{Dignitas,Laudatio}', '{}', 'honor.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Honor'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Anima', 'Anima means soul or spirit, the essence of a person or living being.', 'ˈa.ni.ma', 'From Latin ''anima'', related to breath and life.', 'He believed that the anima lived on after death.', 'Credidit animam post mortem vivere.', 'Her music seemed to have an anima of its own.', 'Musica eius animam propriam habere videbatur.', 'The anima of the forest was palpable at night.', 'Anima silvae nocte palpabilis erat.', '{Spiritus,Mens}', '{}', 'anima.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Anima'));
