-- Insert 20 new generated words (batch 7)

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Emolumentum', 'Emolumentum means a benefit or gain obtained from employment or position.', 'e-mo-loo-men-tum', 'Derived from the Latin term ''emolere'', meaning ''to grind out'' or ''produce by grinding''.', 'The emolumentum from the new project was significantly higher than expected.', 'Emolumentum ex novo proposito multo maius quam exspectatum fuit.', 'He sought an increase in his emolumentum after successfully completing the contract.', 'Incrementum emolumenti sui post contractum feliciter peractum quaesivit.', 'The board discussed the emolumentum packages for senior executives.', 'Tabula de emolumentis seniorum exsecutivorum tractavit.', '{beneficium,lucrum}', '{}', 'emolumentum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Emolumentum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Os', 'Os means a bone or the hard structure that supports the body.', 'os', 'Derived from the Proto-Indo-European root ''ost-'', meaning ''bone''.', 'The archaeologist uncovered an ancient os beneath the ruins.', 'Archaeologus os antiquum sub ruinis detexit.', 'She fractured an os in her wrist during the fall.', 'Os in carpo suo in casu fregit.', 'The doctor examined the os to determine the extent of the injury.', 'Medicus os examinavit ut iniuriae magnitudinem determinaret.', '{ossa,skeleton}', '{}', 'os.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Os'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Copia', 'Copia means an abundance or ample supply of something.', 'ko-pee-a', 'From Latin ''copia'', meaning ''abundance'' or ''plenty''.', 'The banquet featured a copia of delicious dishes.', 'Convivium copiam ferculorum deliciosorum praebuit.', 'A copia of resources was gathered for the upcoming project.', 'Copia rerum ad novum propositum colligebatur.', 'During harvest season, there is a copia of fresh produce.', 'Tempore messis, copia fructuum recentium est.', '{abundantia,plentitudo}', '{penuria,inopia}', 'copia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Copia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Cultus', 'Cultus means cultivation, care, or worship.', 'kul-toos', 'Derived from Latin, from ''colere'', meaning ''to till or cultivate''.', 'The cultus of the land was essential for a successful harvest.', 'Cultus terrae erat essentialis ad messem prosperam.', 'His cultus of the arts was evident in his extensive collection.', 'Eius cultus artium in ampla collectione apparuit.', 'The ancient tribes held a deep cultus towards nature and its spirits.', 'Antiquae tribus profundum cultum erga naturam et spiritus eius habuerunt.', '{cultura,curatio}', '{neglectus}', 'cultus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Cultus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Clavis', 'Clavis means a key, an instrument for opening locks.', 'kla-viss', 'From Latin ''clavis'', which translates to ''key''.', 'He turned the clavis in the lock to open the door.', 'Clavem in seram vertit ut ianuam aperiret.', 'The clavis to unlock the treasure chest was hidden for centuries.', 'Clavis ad thesaurum aperiendum per saecula abscondita erat.', 'During the ceremony, she was handed the city clavis as a symbol of authority.', 'In caerimonia, clavis urbis ei tradita est ut symbolum auctoritatis.', '{serratura,apertura}', '{}', 'clavis.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Clavis'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Opprobrium', 'Opprobrium means a state of disgrace resulting from public abuse.', 'o-pro-bree-um', 'Derived from Latin ''opprobrum'', meaning ''disgrace''.', 'The politician faced opprobrium for his controversial statements.', 'Politicus opprobrium ob controversas sententias passus est.', 'After the scandal, she lived in opprobrium and avoided the public eye.', 'Post scandalum, in opprobrio vixit et oculos publicos evitavit.', 'The failure of the project brought opprobrium to the company.', 'Defectus propositi opprobrium societati attulit.', '{ignominia,infamia}', '{honor,laudatio}', 'opprobrium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Opprobrium'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Iter', 'Iter means a journey or the act of traveling from one place to another.', 'it-er', 'From Latin ''iter'', meaning ''journey or path''.', 'Their iter across the mountains was filled with challenges.', 'Eorum iter per montes plenus erat provocationibus.', 'The iter to the city takes approximately three hours by car.', 'Iter ad urbem circiter tres horas curru capit.', 'She recorded every detail of her iter in a travel journal.', 'Omnem partem itineris sui in diario itinerario descripsit.', '{peregrinatio,viaticum}', '{}', 'iter.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Iter'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Impetus', 'Impetus means a driving force or impulse.', 'im-peh-tus', 'Derived from Latin ''impetus'', meaning ''attack or assault''.', 'The new policy provided an impetus for economic growth.', 'Nova consilium impetus ad incrementum oeconomicum praebuit.', 'Her passion for justice was the main impetus behind her legal career.', 'Eius iustitiae studium erat impetus principalis post eius curriculum legale.', 'The grant acted as an impetus for the research study.', 'Donatio ut impetus pro studio investigationis functa est.', '{incitamentum,impulsus}', '{}', 'impetus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Impetus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Vitis', 'Vitis means grapevine or vine, often signifying the plant that bears grapes.', 'WI-tis', 'From Latin ''vitis'' meaning vine or grapevine.', 'The farmers pruned the vitis to ensure a healthy crop of grapes.', 'Agricolae vitis putaverunt ut messis uvarum sanus esset.', 'He admired the sprawling vitis covering the ancient stone wall.', 'Vitem super antiquam parietem lapideum se diffundentem admiratus est.', 'A vitis can thrive in various climates, providing a rich harvest of grapes.', 'Vitis in variis climatibus vigere potest, copiosam uvarum messem praebens.', '{Vinea,Uva}', '{}', 'vitis.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Vitis'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Orbis', 'Orbis means a circle or a sphere, often used to describe the world or universe in Latin literature.', 'OR-bis', 'From the Latin root ''orbis'', meaning circle.', 'The Earth was depicted as an orbis by ancient Roman scholars.', 'Terra ut orbis a Romanis antiquis depicta est.', 'In Roman maps, the orbis was often surrounded by oceans.', 'In tabulis Romanis, orbis saepe oceanis circumdatus erat.', 'The orbis of stars glittered in the night sky.', 'Orbis stellarum in caelo nocturno micabat.', '{circulus,globus}', '{}', 'orbis.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Orbis'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Cerasus', 'Cerasus means cherry tree or cherry, often denoting the fruit-bearing tree in Latin texts.', 'ke-RAS-us', 'Comes from Ancient Greek ''kerasos'', meaning cherry.', 'The garden was filled with blossoming cerasus in spring.', 'Hortus florentibus cerasis in vere plenus erat.', 'She picked a ripe cerasus from the tree.', 'Maturam cerasum ex arbore decerpsit.', 'The cerasus flowers marked the beginning of the season.', 'Cerasorum flores initium temporis notaverunt.', '{prunus,avium}', '{}', 'cerasus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Cerasus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Alauda', 'Alauda means lark, referring to the small songbird known for its melodious singing.', 'a-LAU-da', 'From the Latin ''alauda'', meaning lark, possibly of Gaulish origin.', 'The morning was filled with the sound of the alauda.', 'Mane sonitu alaudae completum erat.', 'Farmers often noticed the alauda before the dawn.', 'Agricolae saepe alaudam ante auroram animadvertebant.', 'She could mimic the song of the alauda perfectly.', 'Carmen alaudae perfecte imitari potuit.', '{avis,passer}', '{}', 'alauda.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Alauda'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Spina', 'Spina means thorn or spine, often used in a botanical or metaphorical context.', 'SPI-na', 'From the Latin ''spina'', meaning thorn or prickle.', 'The rose bush was covered in sharp spina.', 'Rosae frutex spinis acutis tectus erat.', 'He compared her words to the spina of a cactus.', 'Verba eius spinis cacti comparavit.', 'The path was blocked by a hedge full of spina.', 'Iter sepimento plenum spinis obstructum erat.', '{aculeus,spiculum}', '{}', 'spina.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Spina'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Sericum', 'Sericum means silk, referring to the luxurious textile that was highly prized in ancient times.', 'SE-ri-cum', 'From the Latin ''sericum'', meaning silk, derived from the ancient Greek ''Sērikós'', relating to the Seres or Chinese.', 'The trader offered fine sericum at the market.', 'Mercator sericum pretiosum in foro obtulit.', 'She wore a gown of shimmering sericum.', 'Illa vestem serici micantis gerebat.', 'The road to the East was known as the Sericum Road.', 'Via ad Orientem Via Serici appellabatur.', '{byssus,bombyx}', '{}', 'sericum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Sericum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Globus', 'Globus means a globe or sphere, often used in describing three-dimensional objects or celestial bodies.', 'GLO-bus', 'From the Latin ''globus'', meaning ball or sphere.', 'The starry sky resembled a vast globus.', 'Caelum stellatum magnum globum simile erat.', 'They studied the map on the globus intently.', 'Tabulam in globo diligenter studuerunt.', 'The glassblower crafted a perfect globus.', 'Vitrius globum perfectum effecit.', '{sphaera,orbis}', '{}', 'globus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Globus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Scriba', 'Scriba means ''scribe'' or ''clerk'', referring to a person who copies out documents or records information.', 'skree-bah', 'From Proto-Italic *skrīb-ā, from Proto-Indo-European *skribh-, meaning ''to scratch, write''.', 'The scriba meticulously recorded the details of the meeting.', 'Scriba diligenter res conventus scripsit.', 'In ancient Rome, a scriba held an essential role in government offices.', 'In Roma antiqua, scriba munus essentiale in officiis publicis tenebat.', 'As a scriba, she spent her days documenting the transactions of the marketplace.', 'Ut scriba, dies suos in foro transactiones documentando egit.', '{scriptor,librarius}', '{}', 'scriba.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Scriba'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Tectum', 'Tectum means ''roof'' or ''ceiling'', describing the covering that forms the top of a building or room.', 'tek-toom', 'From Proto-Italic *tek-to-, meaning ''roof, covering'', from Proto-Indo-European *teg- meaning ''to cover''.', 'The tectum of the ancient villa was adorned with intricate mosaics.', 'Tectum villae antiquae intricatis musivis ornatum erat.', 'During the storm, they sought shelter under the sturdy tectum of a barn.', 'Tempestate, sub tecto valido horrei refugium quaesiverunt.', 'The leaking tectum needed urgent repairs before the rainy season began.', 'Tectum manans celeribus reparationibus ante tempus pluviosum indigebat.', '{culmen,summum}', '{}', 'tectum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Tectum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Fenestra', 'Fenestra means ''window'', a structural opening in a wall that allows light and air into a building.', 'feh-nes-trah', 'From Proto-Italic *fenestrā, likely derived from Proto-Indo-European *bʰeh₂- meaning ''to light''.', 'She opened the fenestra to let in the fresh spring air.', 'Illa fenestram aperuit ut aerem vernum recentem admitteret.', 'The architect designed the building with large fenestrae to maximize natural light.', 'Architectus aedificium cum magnis fenestris designavit ut lumen naturale maximaret.', 'Through the fenestra, he could see the bustling city below.', 'Per fenestram, urbem ferventem infra videre potuit.', '{specularia,lunus}', '{}', 'fenestra.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Fenestra'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Mensis', 'Mensis means ''month'', representing one of the twelve divisions of the calendar year.', 'men-sis', 'From Proto-Italic *mēnseis, derived from Proto-Indo-European *mḗh₁n̥s- meaning ''moon, month''.', 'Each mensis brings a new set of challenges and opportunities.', 'Quisque mensis novas provocationes et opportunitates affert.', 'The festival was celebrated in the mensis of December.', 'Festum celebratum est mense Decembri.', 'Farmers often plan their activities according to the cycles of the mensis.', 'Agricolae saepe suas actiones secundum mensium circulos disponunt.', '{luna,menstruus}', '{}', 'mensis.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Mensis'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Carcer', 'Carcer means a prison or jail, a place where individuals are held as a form of punishment or detention. It can also metaphorically refer to any situation in which someone feels confined or trapped.', 'ˈkar.ker', 'From Latin ''carcer'', related to the Proto-Indo-European root *(s)ker- meaning ''to turn, to twist''.', 'After his arrest, the thief was taken to the carcer to await trial.', 'Post arrestationem, fur ad carcerem ductus est ut iudicium exspectaret.', 'In her novel, the protagonist''s carcer became both a physical and mental prison.', 'In suo libro, carcer protagonistis factus est et vinculum corporis et animi.', 'The reformers campaigned for better conditions within the carcer system.', 'Reformatores pro melioribus condicionibus intra systema carceris militaverunt.', '{cella,claustrum}', '{}', 'carcer.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Carcer'));
