-- Insert 10 new generated words (batch 8)

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Zelotypia', 'Zelotypia means jealousy, referring to the emotion of coveting another''s possessions or achievements.', 'ze-loh-TI-pee-ah', 'From Latin ''zelus'', meaning zeal, and ''typia'', a suffix indicating condition.', 'Zelotypia can damage personal relationships if not controlled.', 'Zelotypia relationes personales laedere potest si non cohibetur.', 'Her zelotypia was evident whenever she saw her colleague receive praise.', 'Zelotypia eius manifesta erat quotiescumque collegam suum laudem accipientem videbat.', 'The story illustrated how zelotypia led to the character''s tragic downfall.', 'Fabula illustravit quomodo zelotypia ad tristem exitum personae duxit.', '{Invidia,Livor}', '{Contentum}', 'zelotypia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Zelotypia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Ludibrium', 'Ludibrium means a joke or a mockery, often used to describe something that is treated with derision or contempt in a playful manner.', 'loo-DEE-bree-um', 'Derived from the Latin verb ''ludere'' meaning ''to play''.', 'The new regulations were so ineffective that they became a ludibrium among the citizens.', 'Regulationes novae tam inefficaces erant ut ludibrium inter cives fierent.', 'Her attempts at diplomacy turned into a ludibrium during the heated meeting.', 'Conatus eius ad diplomatiam in ludibrium in conventu calido conversi sunt.', 'The play was intentionally written as a ludibrium to criticize the political leaders of the time.', 'Ludibrium scripta est fabula ad duces politicos temporis criticandos.', '{Iocus,Irrisio}', '{}', 'ludibrium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Ludibrium'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Fulguratio', 'Fulguratio means the act of lightning or a flash of lightning.', 'ful-goo-RAH-tee-oh', 'Derived from the Latin ''fulgur'', meaning lightning.', 'The sudden fulguratio illuminated the night sky.', 'Subita fulguratio caelum nocturnum illustravit.', 'Fulguratio can cause power outages and tree damage.', 'Fulguratio potest causare defectus potentiae et damnum arboribus.', 'Seeing a fulguratio from a safe distance can be a mesmerizing experience.', 'Fulgurationem ex loco tuto spectare potest esse experientia fascinans.', '{Fulmen,Fulgor}', '{}', 'fulguratio.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Fulguratio'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Lacuna', 'Lacuna means a gap or missing part, often used to describe an absence in a manuscript or text.', 'la-KOO-nah', 'From Latin ''lacuna'', originally meaning a ditch or gap.', 'The historian discovered a lacuna in the ancient manuscript.', 'Historicus lacunam in manuscripto antiquo invenit.', 'After the renovation, there was a lacuna in the garden where the old tree stood.', 'Post renovationem, lacuna in horto erat ubi arbor vetus stetit.', 'The author left a lacuna in the plot for readers to interpret.', 'Auctor lacunam in argumento reliquit ut lectores interpretarentur.', '{Hiatus,Intervallum}', '{}', 'lacuna.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Lacuna'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Osseus', 'Osseus means made of or relating to bone.', 'OSS-ee-oos', 'Derived from Latin ''os'', meaning bone.', 'The museum displayed an osseus structure of a dinosaur.', 'Museum structuram osseam dinosaurii exhibuit.', 'The artist created an osseus sculpture that captivated the audience.', 'Artifex sculpturam osseam creavit quae audientiam captivavit.', 'Osseus materials are often sturdy and long-lasting.', 'Materia ossea saepe firma et diuturna est.', '{Ossuus,Osseus}', '{}', 'osseus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Osseus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Plenilunium', 'Plenilunium means the time of the full moon.', 'ple-ni-LOO-nee-um', 'From Latin ''plenus'', meaning full, and ''luna'', meaning moon.', 'Many ancient cultures held festivals during the plenilunium.', 'Multae culturae antiquae festa tempore plenilunii celebrabant.', 'The plenilunium cast a silvery glow over the landscape.', 'Plenilunium argenteum splendorem super landscape iaciebat.', 'During the plenilunium, tides tend to be stronger.', 'Tempore plenilunii, aestus tendunt esse fortiores.', '{Plenilune,Lunaris}', '{}', 'plenilunium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Plenilunium'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Rapacitas', 'Rapacitas means greed or avarice, referring to an excessive desire for wealth.', 'ra-PAH-ci-tas', 'From Latin ''rapere'', meaning to seize or take.', 'Rapacitas can lead individuals to make unethical decisions.', 'Rapacitas potest homines ad decisiones inhonestas ducere.', 'The downfall of the corporation was attributed to rapacitas among its leaders.', 'Ruinam corporationis rapacitas inter duces eius attribuitur.', 'Political history is often marred by rapacitas and corruption.', 'Historia politica saepe rapacitate et corruptione maculatur.', '{Avaritia,Cupido}', '{Liberalitas,Generositas}', 'rapacitas.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Rapacitas'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Tertius', 'Tertius means third, often used to indicate the third in a series or sequence.', 'TER-tee-oos', 'From Latin ''tertio'', meaning third.', 'The tertius chapter of the book provided a major plot twist.', 'Tertius liber capitulum maiorem fabulae conversionem praebuit.', 'He finished in the tertius position in the race.', 'In tertia positione in cursu finivit.', 'The tertius day of the festival was the most exciting.', 'Tertius dies festi maxime excitans erat.', '{Tertium,Tertia}', '{}', 'tertius.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Tertius'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Ursus', 'Ursus means bear, referring to the large mammal known for its strength and thick fur.', 'UR-sus', 'From Latin ''ursus'', meaning bear.', 'Ursus appeared frequently in Roman mythology as a symbol of strength.', 'Ursus frequenter in mythologia Romana apparuit ut symbolum fortitudinis.', 'The family watched the ursus from a safe distance in the woods.', 'Familia ursum e loco tuto in silvis spectavit.', 'The zoo''s newest attraction was a playful ursus from the Arctic.', 'Novissima attractio zoologici erat ludens ursus ex Arctico.', '{Arctos,Balaena}', '{}', 'ursus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Ursus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Vexillum', 'Vexillum means a flag or banner, often used to denote military or group affiliation.', 'vek-SIL-lum', 'From Latin ''vexillum'', a diminutive of ''velum'', meaning sail or banner.', 'The soldiers marched behind the vexillum with pride.', 'Milites post vexillum cum superbia processerunt.', 'During the parade, every division carried its own vexillum.', 'In pompa, omnis divisio suum vexillum portavit.', 'The vexillum fluttered brightly in the morning breeze.', 'Vexillum in aura matutina clare fluitavit.', '{Signum,Labrum}', '{}', 'vexillum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Vexillum'));
