-- Insert 10 new generated words (batch 9)

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Alacritas', 'Alacritas means enthusiasm or eagerness in doing something.', 'a-la-kri-tas', 'Latin alacritas, from alacer meaning lively or eager.', 'Her alacritas in tackling the project impressed everyone in the team.', 'Alacritas eius in incepto aggrediendo omnes in turma impressit.', 'The alacritas of the students was evident as they eagerly volunteered for the science experiment.', 'Alacritas discipulorum manifesta erat dum ad experimentum scientificum libenter se obtulerunt.', 'His alacritas was infectious, motivating the entire crew to work with zest.', 'Alacritas eius contagiosa erat, totum gregem ad opus cum studio incitans.', '{celeritas,vivacitas}', '{indolentia,pigritia}', 'alacritas.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Alacritas'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Solum', 'Solum means ground or soil, referring to the earth underfoot.', 'so-lum', 'Latin solum, meaning ground or soil.', 'The solum was fertile and perfect for planting crops.', 'Solum erat fertile et perfectum ad plantas serendas.', 'Archaeologists examined the solum for ancient artifacts.', 'Archaeologi solum ad antiqua artificia examinaverunt.', 'The solum in this region is rich with minerals.', 'Solum in hac regione divitum mineralibus est.', '{terra,humus}', '{}', 'solum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Solum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Tentatio', 'Tentatio means trial or temptation, referring to a test of one''s character or resolve.', 'ten-ta-tio', 'Latin tentatio, from ''tentare'' meaning to try or attempt.', 'The desert journey was a true tentatio of endurance.', 'Iter per desertum vera tentatio patientiae erat.', 'He faced many tentatio on his path to success.', 'Multas tentationes in via ad successum passus est.', 'The actors'' tentatio was an opportunity to showcase their skills.', 'Actorum tentatio occasio erat artes suas ostendere.', '{periculum,experimentum}', '{}', 'tentatio.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Tentatio'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Valetudo', 'Valetudo means health or well-being, referring to the condition of being physically and mentally sound.', 'wa-le-tu-do', 'From Latin ''valetudo'', related to ''valere'' meaning to be strong or healthy.', 'She maintained her valetudo with regular exercise and a balanced diet.', 'Valetudinem suam exercitatione regulari et dieta aequilibrata servavit.', 'The retreat focused on improving both mental and physical valetudo.', 'Secessus ad valetudinem mentis et corporis meliorem spectavit.', 'Valetudo is wealth, as the proverb suggests.', 'Valetudo est divitiae, ut proverbium suggerit.', '{salus,sanitas}', '{morbus,infirmitas}', 'valetudo.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Valetudo'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Spero', 'Spero means ''I hope'' or ''I expect'' in Latin, signifying a sense of anticipation or optimism.', 'speh-roh', 'From the Latin verb ''sperare,'' meaning ''to hope.''', 'Spero that tomorrow''s weather will be favorable.', 'Spero ut crastini dies tempestas favens sit.', 'The adventurer spero to discover new lands.', 'Adventor spero novas terras detegere.', 'In troubling times, she clung to spero for better days.', 'In temporibus difficilibus, ad speronem meliorum dierum adhaesit.', '{Expecto,Confido}', '{}', 'spero.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Spero'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Litus', 'Litus means ''shore'' or ''coast'' in Latin, referring to the land along the edge of a sea, lake, or other large body of water.', 'lee-toos', 'Derived from the Latin verb ''linere,'' meaning ''to smear,'' possibly relating to the meeting of water and land.', 'The litus was dotted with shells and seaweed.', 'Litus conchis et alga sparsum erat.', 'Artists loved to capture the beauty of the litus at sunrise.', 'Artifices amabant pulchritudinem litus ad ortum solis depingere.', 'Walking along the litus, they enjoyed the sound of waves crashing.', 'Per litus ambulantes, sonum fluctuum frangentium gavisi sunt.', '{Ora,Ripa}', '{}', 'litus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Litus'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Charta', 'Charta means paper or a document that is written on.', 'ˈkar.ta', 'Derived from Greek ''khartēs'' meaning papyrus or paper.', 'The charta was filled with the scribbles of ancient scholars.', 'Charta erat plena scriptis antiquorum scholarium.', 'She carefully rolled up the charta and placed it in a safe container.', 'Diligenter chartam involvit et in tuto loco posuit.', 'A charta was presented as evidence during the trial.', 'Charta ut testimonium in iudicio praesentata est.', '{Codex,Liber}', '{}', 'charta.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Charta'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Carior', 'Carior means ''dearer'' or ''more precious'', usually referring to something cherished or valued highly.', 'KAHR-ee-or', 'Derived from the Latin adjective ''carus'', meaning ''dear'' or ''beloved''.', 'Family photos are carior to her after the loss of her parents.', 'Photographiae familiae sunt cariores ei post parentum amissionem.', 'The old watch became carior to him as a family heirloom.', 'Vetus horologium carior ei factus est ut hereditas familiae.', 'Experiences are carior than material things to him.', 'Experientiae sunt cariores quam res materiales ei.', '{Pretiosus,Amabilis}', '{Vilior}', 'carior.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Carior'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Gelum', 'Gelum means ''frost'' or ''chill'', often used to describe cold weather conditions or a figurative emotional coldness.', 'GAY-lum', 'From the Latin verb ''gelare'', meaning ''to freeze''.', 'The morning gelum covered the city in a sparkling layer of ice.', 'Matutinum gelum urbem strato nitido glaciei texit.', 'There was a gelum in his voice when he spoke of their past.', 'Gelum in voce eius erat cum de praeteritis loquebatur.', 'The gelum of the Arctic wind cut through her coat.', 'Gelum venti arctici per tunicam eius secuit.', '{Frigus,Glacies}', '{}', 'gelum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Gelum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Silicium', 'Silicium means a chemical element with the symbol Si and atomic number 14, commonly known as silicon. It is a hard and brittle crystalline solid with a blue-grey metallic lustre, primarily used in electronics and computer chips.', 'si-LEE-kee-um', 'The word ''silicium'' is derived from the Latin ''silex'' or ''silicis'', meaning flint or hard stone, due to its natural occurrence in a rock-hard state.', 'Silicium is a fundamental element in the manufacturing of semiconductors.', 'Silicium elementum fundamentale in fabricandis semiconductoribus est.', 'Thanks to silicium, computer processors have become more efficient and faster.', 'Gratia silicii, processus computatrorum efficientiores et velociores facti sunt.', 'The abundance of silicium in the Earth''s crust makes it crucial for the production of glass and ceramics.', 'Abundantia silicii in crusta Telluris id ad productionem vitri et ceramicorum crucialem facit.', '{Silicon,Elementum}', '{}', 'silicium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Silicium'));
