-- Insert 15 new generated words (batch 10)

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Aequitas', 'Aequitas means fairness or equity, referring to the principle of justice and impartial treatment.', 'EYE-kwi-tahs', 'From Latin ''aequus'' meaning equal or level, giving rise to the concept of balanced justice.', 'The judge was known for her unwavering commitment to aequitas in every ruling.', 'Iudex nota erat ob constantem fidem aequitati in omni sententia.', 'True leadership requires aequitas when resolving disputes among team members.', 'Vera auctoritas aequitatem requirit cum controversias inter sodales componit.', 'The philosopher argued that aequitas is the foundation of a just society.', 'Philosophus contendit aequitatem fundamentum iustae civitatis esse.', '{Iustitia,Ius}', '{Iniquitas,Iniuria}', 'aequitas.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Aequitas'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Audacia', 'Audacia means boldness or daring, describing the courage to take risks or act fearlessly.', 'ow-DAH-kee-ah', 'From Latin ''audax'' meaning bold or daring, derived from ''audere'' meaning to dare.', 'Her audacia in challenging the established order inspired a generation.', 'Audacia eius in ordine constituto provocando generationem inspiravit.', 'The explorer''s audacia led him to discover uncharted lands.', 'Audacia exploratoris eum ad terras incognitas inveniendas duxit.', 'Without audacia, no great invention would ever have been realized.', 'Sine audacia, nulla magna inventio umquam effecta esset.', '{Fortitudo,Animus}', '{Timor,Timiditas}', 'audacia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Audacia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Custos', 'Custos means guardian or watchman, referring to one who protects or watches over something.', 'KOO-stohs', 'From the Latin root ''custodire'' meaning to guard or protect.', 'The custos of the ancient library ensured that every scroll was preserved.', 'Custos bibliothecae antiquae curavit ut omnis volumen servaretur.', 'Like a faithful custos, the shepherd watched over his flock through the night.', 'Sicut fidelis custos, pastor gregem suum per noctem custodivit.', 'The city appointed a custos to oversee the restoration of the historic temple.', 'Civitas custodem designavit ad instaurationem templi historici curandam.', '{Vigil,Praeses}', '{}', 'custos.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Custos'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Dulcis', 'Dulcis means sweet or pleasant, used to describe something that is delightful to the senses or spirit.', 'DOOL-kis', 'From Latin ''dulcis'' meaning sweet, also the root of English words like ''dulcet''.', 'The dulcis melody of the harp filled the evening air.', 'Dulcis melodia citharae vespertinum aera implevit.', 'She remembered the dulcis taste of honey from her grandmother''s garden.', 'Dulcem saporem mellis ex horto aviae suae meminit.', 'His dulcis words calmed her fears during the storm.', 'Dulcia verba eius timores per tempestatem sedaverunt.', '{Suavis,Iucundus}', '{Amarus,Acerbus}', 'dulcis.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Dulcis'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Fortuna', 'Fortuna means fortune or luck, referring to the force that brings good or ill to people, often personified as a goddess in Roman religion.', 'for-TOO-nah', 'From Latin ''fors'' meaning chance or luck. Fortuna was the Roman goddess of fortune and fate.', 'By a stroke of fortuna, the lost manuscript was discovered in an attic.', 'Fortuito casu fortuna, manuscriptum amissum in cenaculo repertum est.', 'The Romans built temples to Fortuna, hoping to gain her favor.', 'Romani templa Fortunae aedificaverunt, favorem eius sperantes.', 'His fortuna changed overnight when he inherited the estate.', 'Fortuna eius una nocte mutata est cum praedium hereditavit.', '{Sors,Fatum}', '{Infortunium}', 'fortuna.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Fortuna'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Gratia', 'Gratia means grace, gratitude, or favor, encompassing both the elegance of movement and the thankfulness one feels toward another.', 'GRAH-tee-ah', 'From Latin ''gratus'' meaning pleasing or thankful, the root of English words like ''grateful'' and ''grace''.', 'The dancer moved with such gratia that the audience was spellbound.', 'Saltatrix tanta gratia movebat ut spectatores obstupefacti essent.', 'He expressed deep gratia to his mentor for years of guidance.', 'Profundam gratiam magistro suo pro annis ducendi expressit.', 'In Roman culture, gratia was considered essential in maintaining social bonds.', 'In cultura Romana, gratia ad vincula socialia conservanda necessaria habebatur.', '{Benevolentia,Elegantia}', '{Ingratitudo}', 'gratia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Gratia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Imperium', 'Imperium means supreme power, command, or empire, referring to the authority to give orders and the domain over which that authority extends.', 'im-PEH-ree-um', 'From Latin ''imperare'' meaning to command. Originally denoted the power of Roman magistrates, later extended to mean empire.', 'The Roman imperium stretched from Britain to Mesopotamia at its peak.', 'Imperium Romanum a Britannia ad Mesopotamiam in summo vigore pertinebat.', 'The general held imperium over all the legions in the eastern provinces.', 'Dux imperium in omnes legiones in provinciis orientalibus tenebat.', 'The concept of imperium shaped the political structure of the ancient world.', 'Conceptus imperii structuram politicam mundi antiqui formavit.', '{Potestas,Regnum}', '{Servitus,Subiectio}', 'imperium.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Imperium'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Lumen', 'Lumen means light or brightness, referring both to physical illumination and figurative enlightenment.', 'LOO-men', 'From Latin ''lumen'' meaning light, related to ''lucere'' meaning to shine. It gives us English words like ''luminous'' and ''illuminate''.', 'A single lumen from the candle was enough to read the ancient text.', 'Unum lumen candelae satis erat ad textum antiquum legendum.', 'The philosopher was considered a lumen of wisdom in his time.', 'Philosophus lumen sapientiae suo tempore habebatur.', 'The morning lumen poured through the stained glass, painting the walls in color.', 'Lumen matutinum per vitrum pictum fluxit, parietes coloribus pingens.', '{Lux,Splendor}', '{Tenebrae,Obscuritas}', 'lumen.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Lumen'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Memoria', 'Memoria means memory or remembrance, the faculty by which the mind stores and recalls past experiences.', 'meh-MOR-ee-ah', 'From Latin ''memor'' meaning mindful, the root of English words like ''memory'', ''memorial'', and ''commemorate''.', 'The veterans gathered to honor the memoria of their fallen comrades.', 'Veterani convenerunt ut memoriam commilitonum mortuorum honorarent.', 'Her memoria of childhood summers spent by the sea never faded.', 'Memoria eius de aestatibus puerilibus ad mare actis numquam evanuit.', 'The Romans believed that preserving memoria through writing was a sacred duty.', 'Romani credebant memoriam per scripturam servare officium sacrum esse.', '{Recordatio,Reminiscentia}', '{Oblivio}', 'memoria.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Memoria'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Pax', 'Pax means peace, referring to a state of tranquility, absence of war, or harmonious relations between people.', 'PAHKS', 'From Latin ''pax'' meaning peace. Pax was also the Roman goddess of peace. The famous Pax Romana described centuries of relative stability.', 'After years of conflict, the two nations finally achieved pax.', 'Post annos conflictus, duae nationes tandem pacem assecutae sunt.', 'The Pax Romana brought unprecedented prosperity to the Mediterranean world.', 'Pax Romana prosperitatem sine exemplo ad mundum Mediterraneum attulit.', 'The garden was a place of pax where she could escape the noise of the city.', 'Hortus locus pacis erat ubi strepitum urbis effugere poterat.', '{Concordia,Tranquillitas}', '{Bellum,Discordia}', 'pax.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Pax'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Prudentia', 'Prudentia means wisdom, foresight, or practical judgment, the ability to discern the right course of action.', 'proo-DEN-tee-ah', 'From Latin ''prudens'' meaning wise or foreseeing, a contraction of ''providens'' meaning one who sees ahead.', 'His prudentia in financial matters saved the company from bankruptcy.', 'Prudentia eius in rebus pecuniariis societatem a ruina servavit.', 'The elder was sought for her prudentia in resolving community disputes.', 'Maior ob prudentiam suam in controversiis communitatis componendis petebatur.', 'Prudentia is one of the four cardinal virtues in classical philosophy.', 'Prudentia una ex quattuor virtutibus cardinalibus in philosophia classica est.', '{Sapientia,Consilium}', '{Stultitia,Imprudentia}', 'prudentia.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Prudentia'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Templum', 'Templum means a temple or sacred space, a building dedicated to the worship of gods or used for religious ceremonies.', 'TEM-plum', 'From Latin ''templum'', originally meaning a space marked out by augurs for observing omens, later meaning a building consecrated to a deity.', 'The templum of Jupiter Optimus Maximus stood atop the Capitoline Hill.', 'Templum Iovis Optimi Maximi in summo Colle Capitolino stabat.', 'Pilgrims traveled great distances to offer prayers at the ancient templum.', 'Peregrini magna itinera fecerunt ut preces in antiquo templo offerrent.', 'The ruins of the templum revealed exquisite carvings and marble columns.', 'Ruinae templi exquisitas sculpturas et columnas marmoreas revelaverunt.', '{Fanum,Delubrum}', '{}', 'templum.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Templum'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Veritas', 'Veritas means truth, referring to the quality of being in accordance with fact or reality.', 'VEH-ri-tahs', 'From Latin ''verus'' meaning true. Veritas was the Roman goddess of truth, depicted as a young woman dressed in white.', 'The motto of the university is a single word: Veritas.', 'Lemma universitatis unum verbum est: Veritas.', 'The witness swore to speak nothing but veritas before the senate.', 'Testis iuravit se nihil nisi veritatem coram senatu dicturum esse.', 'Philosophers have debated the nature of veritas for millennia.', 'Philosophi naturam veritatis per milia annorum disputaverunt.', '{Fides,Sinceritas}', '{Mendacium,Falsitas}', 'veritas.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Veritas'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Victoria', 'Victoria means victory or conquest, the achievement of success in a struggle or competition.', 'wik-TOR-ee-ah', 'From Latin ''vincere'' meaning to conquer. Victoria was the Roman goddess of victory, equivalent to the Greek Nike.', 'The general celebrated his victoria with a grand triumph through the streets of Rome.', 'Dux victoriam suam magno triumpho per vias Romae celebravit.', 'Her victoria in the debate competition earned her a scholarship.', 'Victoria eius in certamine disputandi ei stipendium meruit.', 'The monument was erected to commemorate the victoria of the allied forces.', 'Monumentum erectum est ad victoriam copiarum foederatarum commemorandam.', '{Triumphus,Palma}', '{Clades,Defectio}', 'victoria.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Victoria'));

INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image)
SELECT 'Virtus', 'Virtus means virtue, courage, or moral excellence, encompassing the qualities of character that make a person admirable.', 'WIR-toos', 'From Latin ''vir'' meaning man, originally denoting manly valor. Over time it broadened to encompass all moral virtues.', 'The Romans considered virtus the highest quality a citizen could possess.', 'Romani virtutem summam qualitatem quam civis habere posset censebant.', 'His virtus on the battlefield earned him the respect of both allies and enemies.', 'Virtus eius in proelio ei respectum et sociorum et hostium meruit.', 'True virtus is not measured by strength alone but by the integrity of one''s character.', 'Vera virtus non sola vi sed integritate morum aestimatur.', '{Probitas,Fortitudo}', '{Vitium,Ignavia}', 'virtus.jpg'
WHERE NOT EXISTS (SELECT 1 FROM word_of_the_day WHERE LOWER(word) = LOWER('Virtus'));
