-- =============================================================
-- V1__seed_words.sql
-- Flyway-style migration: creates the word_of_the_day table
-- and seeds it with Latin vocabulary words.
-- =============================================================

CREATE TABLE IF NOT EXISTS word_of_the_day (
    id SERIAL PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    definition TEXT NOT NULL,
    pronunciation VARCHAR(255),
    origin VARCHAR(255),
    example0 TEXT,
    example0_latin TEXT,
    example1 TEXT,
    example1_latin TEXT,
    example2 TEXT,
    example2_latin TEXT,
    synonyms TEXT[],
    antonyms TEXT[],
    image VARCHAR(255)
);

-- Seed data
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Mare', 'Mare means ''sea'' and refers to a large body of salt water that is surrounded in whole or in part by land.', 'MAH-reh', 'From Proto-Indo-European *móri, related to Latin ''Maria'', meaning large body of water.', 'The sailors navigated across the vast sea.', 'Nautae trans magnum mare navigaverunt.', 'The sea was calm and serene at dawn.', 'Mare tranquillum et serenum aurora erat.', 'She gazed at the endless horizon of the sea.', 'Aspiciebat ad infinitum horizontem maris.', ARRAY['Oceanus', 'Pelagus'], ARRAY[]::TEXT[], 'mare.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Amor', 'Amor means ''love'', describing a profound feeling of affection and attachment.', 'AH-mor', 'From Latin ''amare'', meaning to love or to hold dear.', 'The poet wrote about eternal love.', 'Poeta de aeterno amore scripsit.', 'Her love for music is evident in everything she does.', 'Amor eius ad musicam patet in omnibus quae facit.', 'They showed their love through kindness and understanding.', 'Amorem suum per benignitatem et intellectum ostenderunt.', ARRAY['Caritas', 'Dilectio'], ARRAY['Odio'], 'amor.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Aqua', 'Water, the basic necessity of life.', 'AH-kwah', 'From Proto-Italic *akwā, derived from Proto-Indo-European *h₂ekweh₂.', 'The clear water fills the cup.', 'Aqua clara poculum implet.', 'A river flows with fresh water.', 'Fluvius aqua recenti fluit.', 'They clean the floor with water.', 'Pavimentum aqua purgant.', ARRAY['Unda', 'Liquor'], ARRAY[]::TEXT[], 'aqua.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Pax', 'Peace, a state of tranquility or quiet.', 'PAHKS', 'From Proto-Italic *paktis, from Proto-Indo-European *peḱ- (''to agree'').', 'The nations seek peace.', 'Gentes pacem quaerunt.', 'Peace reigns in the city.', 'Pax in urbe regnat.', 'His heart is filled with peace.', 'Cor eius pace plenus est.', ARRAY['Quies', 'Tranquillitas'], ARRAY['Bellum'], 'pax.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Rex', 'King, the male ruler of an independent state.', 'REHKS', 'From Proto-Italic *rēks, from Proto-Indo-European *h₃rḗǵs (''ruler'').', 'The king leads his people.', 'Rex populum suum ducit.', 'A wise king is beloved.', 'Rex sapiens amatur.', 'The king holds court.', 'Rex curiam tenet.', ARRAY['Monarch', 'Regis'], ARRAY['Servus'], 'rex.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Arbor', 'Tree, a perennial plant with an elongated stem or trunk.', 'AR-bor', 'From Proto-Italic *arɸōs, from Proto-Indo-European *h₂erdʰ- (''to grow'').', 'The tree''s shade is refreshing.', 'Umbra arboris refrigerat.', 'Birds nest in the tree.', 'Aves in arbore nidificant.', 'The tree grows strong and tall.', 'Arbor fortis et alta crescit.', ARRAY['Silva', 'Frutex'], ARRAY[]::TEXT[], 'arbor.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Terra', 'Earth, the land surface of the world.', 'TEHR-ra', 'From Proto-Italic *tersā, from Proto-Indo-European *ters- (''dry'').', 'They cultivate the earth.', 'Terram colunt.', 'The earth is fertile and green.', 'Terra fertilis et viridis est.', 'He marks his territory.', 'Territorium suum notat.', ARRAY['Humus', 'Ager'], ARRAY[]::TEXT[], 'terra.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Fortuna', 'Fortune, chance or luck regarded as an external arbitrary force.', 'for-TOO-nah', 'From Proto-Italic *fortonā, possibly from Proto-Indo-European *bher- (''to carry'').', 'Fortune favors the brave.', 'Fortuna fortes adiuvat.', 'He takes a risk for fortune.', 'Periculum pro fortuna capiet.', 'Her fortune has changed suddenly.', 'Fortuna eius subito mutata est.', ARRAY['Sors', 'Casus'], ARRAY[]::TEXT[], 'fortuna.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Insula', 'Island, a tract of land surrounded by water.', 'IN-su-lah', 'From Proto-Italic *enisalā, likely from Proto-Indo-European *eynsula (''island'').', 'The island is lush and green.', 'Insula virens et florida est.', 'They sailed to a distant island.', 'Ad insulam longinquam navigaverunt.', 'The island is surrounded by cliffs.', 'Insula rupibus circumdata est.', ARRAY['Aegyptus', 'Naso'], ARRAY[]::TEXT[], 'insula.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Stella', 'Star, a luminous point in the night sky.', 'STEL-lah', 'From Proto-Italic *stelhā, from Proto-Indo-European *h₂stḗr (''star'').', 'Stars shine brightly at night.', 'Stellae noctu lucent.', 'The star guides the sailors.', 'Stella nautas ducit.', 'She wishes upon a falling star.', 'Super stellam cadentem votum facit.', ARRAY['Astrum', 'Sidus'], ARRAY[]::TEXT[], 'stella.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Ignis', 'Fire, the phenomenon of combustion manifested in light, flame, and heat.', 'IG-nis', 'From Proto-Italic *ignis, from Proto-Indo-European *h₁n̥gʷnís (''fire'').', 'Fire warms the hall.', 'Ignis atrium calefacit.', 'The fire blazes brightly.', 'Ignis lucidus ardent.', 'They gathered around the fire.', 'Circa ignem convenerunt.', ARRAY['Flamma', 'Focus'], ARRAY['Aqua'], 'ignis.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Lux', 'Light, the natural agent that stimulates sight and makes things visible.', 'LUKS', 'From Proto-Italic *louks, from Proto-Indo-European *lówkʷs (''light'').', 'Light illuminates the room.', 'Lux conclave illuminat.', 'The dawn brings light.', 'Aurora lucem affert.', 'They follow the light of the lantern.', 'Lucem lanternae sequuntur.', ARRAY['Lumen', 'Clarus'], ARRAY['Tenebrae'], 'lux.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Vitrum', 'Glass, a hard, brittle substance typically transparent or translucent.', 'VIH-trum', 'From Latin vitrum, of uncertain origin but possibly related to vītus (''life'').', 'The glass was filled with water.', 'Vitrum aqua impletum erat.', 'He looked through the clear glass.', 'Per vitrum clarum aspexit.', 'Glass can shatter easily.', 'Vitrum facile frangi potest.', ARRAY['Crystallum', 'Speculum'], ARRAY[]::TEXT[], 'vitrum.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Fluctus', 'Wave, a long body of water curling into an arched form and breaking on the shore.', 'FLUK-tus', 'From Latin, based on fluo (''flow'').', 'Waves crash on the beach.', 'Fluctus in litus impingunt.', 'The waves are strong today.', 'Fluctus hodie fortes sunt.', 'He watched the waves from the shore.', 'A litore fluctus spectabat.', ARRAY['Unda', 'Mari'], ARRAY[]::TEXT[], 'fluctus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Silva', 'Forest, a large area covered chiefly with trees and undergrowth.', 'SIL-wah', 'From Proto-Italic *silwā, from Proto-Indo-European *selu- (''wood, forest'').', 'The forest is dense and mysterious.', 'Silva densa et mystica est.', 'Animals thrive in the forest.', 'Animalia in silva florent.', 'She wandered through the forest.', 'Per silvam erravit.', ARRAY['Nemus', 'Lucus'], ARRAY[]::TEXT[], 'silva.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Aurora', 'Dawn, the first light of day.', 'ow-ROH-rah', 'From Latin aurora (''dawn''), associated with the goddess of dawn.', 'The dawn heralds a new day.', 'Aurora novum diem praenunciat.', 'Aurora tinges the sky with colors.', 'Aurora caelum coloribus tingit.', 'He rose with the dawn.', 'Cum aurora surrexit.', ARRAY['Diluculum', 'Ortus'], ARRAY[]::TEXT[], 'aurora.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Gladius', 'Sword, a weapon with a long blade for cutting or thrusting.', 'GLAH-dee-us', 'From Proto-Italic *gladios, possibly from Proto-Indo-European *gʷlh₂tós (''stab, cut'').', 'The sword glints in the sunlight.', 'Gladius in sole micat.', 'He clenched the sword tightly.', 'Gladium strenue tenuit.', 'The sword was passed down through generations.', 'Gladius generibus traditus est.', ARRAY['Spatha', 'Ensis'], ARRAY[]::TEXT[], 'gladius.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Uxor', 'Wife, a married woman considered in relation to her spouse.', 'OOK-sore', 'From Proto-Italic *ukᶅisōr, from Proto-Indo-European *ukʷs- (''female'').', 'The wife supported her husband.', 'Uxor maritum adiuvit.', 'She attends the gathering with her wife.', 'Cum uxore convivium frequentat.', 'He spoke fondly of his wife.', 'De uxore sua amanter locutus est.', ARRAY['Coniunx', 'Mulier'], ARRAY[]::TEXT[], 'uxor.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Vita', 'Life, the existence of an individual human being or animal.', 'WIH-tah', 'From Proto-Italic *wītā, from Proto-Indo-European *gʷih₃wós (''alive'').', 'Life is full of adventures.', 'Vita plena est adventuris.', 'She cherishes every moment of her life.', 'Omne momentum vitae suae colit.', 'He leads a simple life.', 'Vitam simplicem ducit.', ARRAY['Anima', 'Existential'], ARRAY['Mors'], 'vita.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Tempus', 'Time, the indefinite continued progress of existence.', 'TEM-pus', 'From Proto-Italic *tempos, derived from Proto-Indo-European *tem- (''to cut'').', 'Time waits for no one.', 'Tempus neminem manet.', 'They marked the passage of time.', 'Transitum temporis notaverunt.', 'Time moves slowly in peaceful moments.', 'In momentis pacificis tempus lente movetur.', ARRAY['Hora', 'Aetas'], ARRAY[]::TEXT[], 'tempus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Silentium', 'Silence, the absence of sound.', 'si-len-TEE-um', 'From Latin silentium.', 'The forest was enveloped in silence.', 'Sylva silentio obtecta erat.', 'Silence fell over the room.', 'Silentium super conclave cecidit.', 'He appreciated the silence of the early morning.', 'Silentium primae matutinum aestimavit.', ARRAY['Taciturnitas', 'Quies'], ARRAY['Clamor'], 'silentium.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Flumen', 'River, a large natural stream of water flowing in a channel to the sea, a lake, or another river.', 'FLOO-men', 'From Latin flūmen, derived from fluō (''flow'').', 'The river flows gently through the valley.', 'Flumen leniter per vallem fluat.', 'He sat by the river and watched the water.', 'Apud flumen sedit et aquam spectavit.', 'Rivers are important for transportation.', 'Flumina sunt ad vecturas magni momenti.', ARRAY['Amnis', 'Rivus'], ARRAY[]::TEXT[], 'flumen.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Spes', 'Hope, a feeling of expectation and desire for a particular thing to happen.', 'SPAYS', 'From Proto-Italic *speh-, from Proto-Indo-European *spek- (''to look, to observe'').', 'Hope springs eternal in the human breast.', 'Spes aeterna in pectore humano oritur.', 'They have hope for a better future.', 'Spem in melior futura habent.', 'Hope gave them strength to continue.', 'Spes eis vim ad pergendum dedit.', ARRAY['Expectatio', 'Confidentia'], ARRAY['Desperatio'], 'spes.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Caelum', 'Sky, the expanse of air over any given point on the earth.', 'KAI-lum', 'From Proto-Italic *kaiwelo-, from Proto-Indo-European *ḱaywelo- (''the act of carving, engraving'').', 'The sky is clear and blue today.', 'Caelum hodie clarum et caeruleum est.', 'He gazed up at the vast sky.', 'Caelum immensum spectavit.', 'Stars fill the sky at night.', 'Stellae caelum noctu replent.', ARRAY['Aer', 'Aethra'], ARRAY[]::TEXT[], 'caelum.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Virtus', 'Courage, the ability to confront pain or fear.', 'WEER-toos', 'From Latin virtus, derived from vir (''man'').', 'Courage is admired in leaders.', 'Virtus in ducibus admiratur.', 'He showed courage in the face of danger.', 'Coram periculo virtutem ostendit.', 'Courage conquers fear.', 'Virtus metum vincit.', ARRAY['Fortitudo', 'Audacia'], ARRAY['Timor'], 'virtus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Somnus', 'Sleep, a state of rest for the mind and body.', 'SOM-noos', 'From Latin somnus, derived from Proto-Indo-European *swep-no- (''to sleep'').', 'Sleep restores the body.', 'Somnus corpus restituit.', 'He drifted into a peaceful sleep.', 'In somnum quietum incidit.', 'Sleep is essential for health.', 'Somnus ad valetudinem necessarius est.', ARRAY['Quietus', 'Dormitio'], ARRAY[]::TEXT[], 'somnus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Poena', 'Punishment, the infliction of a penalty as retribution for an offense.', 'POY-nah', 'From Latin poena, from Greek poinē (''penalty, recompense, punishment'').', 'Justice demands punishment for crime.', 'Iustitia poenam pro crimine postulat.', 'The punishment was severe.', 'Poena gravis erat.', 'He faced punishment for his actions.', 'Propter acta sua poenam sustinuit.', ARRAY['Supplicium', 'Multa'], ARRAY[]::TEXT[], 'poena.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Vox', 'Voice, the sound produced in a person’s larynx and uttered through the mouth.', 'VOHKS', 'From Proto-Italic *wōks, from Proto-Indo-European *wekʷ- (''to speak'').', 'Her voice was soothing.', 'Vox eius lenis erat.', 'The singer shared his voice with many.', 'Cantor vocem suam multis communicavit.', 'Voices echoed in the hall.', 'Voces in aula resonabant.', ARRAY['Clamor', 'Sonus'], ARRAY[]::TEXT[], 'vox.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Aetas', 'Age, the length of time a person has lived.', 'AY-tahs', 'From Latin aetas, from aevum (''eternity, age'').', 'With age comes wisdom.', 'Cum aetate sapientia venit.', 'He felt the weight of his age.', 'Aetatis pondus sensit.', 'Age is just a number.', 'Aetas tantum numerus est.', ARRAY['Saeculum', 'Tempus'], ARRAY[]::TEXT[], 'aetas.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Lumen', 'Light, the natural agent that makes things visible.', 'LOO-men', 'From Latin lumen, from Proto-Indo-European *low-men- (''light, brightness'').', 'The lamp provided light for reading.', 'Lumen ad legendum lucem praebuit.', 'Light shone through the window.', 'Lumen per fenestram resplenduit.', 'The light of the moon was soft and gentle.', 'Lumen lunae lene at placidum erat.', ARRAY['Lux', 'Claritas'], ARRAY['Tenebrae'], 'lumen.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Iuvenis', 'Youth, the period between childhood and adult age.', 'YOO-veh-nis', 'From Proto-Italic *juwenī, from Proto-Indo-European *yuHwen- (''young'').', 'Youth is full of potential.', 'Iuventus plenus potentiae est.', 'She celebrated her youthful spirit.', 'Spiritum iuvenilem celebravit.', 'The youth gathered in the park.', 'Iuvenes in parco convenerunt.', ARRAY['Adulescentia', 'Pueritia'], ARRAY['Senectus'], 'iuvenis.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Felicitas', 'Happiness, the state of being happy.', 'feh-LIHS-i-tahs', 'From Latin felicitas, from felix (''happy, lucky'').', 'Happiness is a warm embrace.', 'Felicitas amplectus calidus est.', 'She found happiness in simple things.', 'Felicitatem in rebus simplicibus invenit.', 'The child''s laughter was pure happiness.', 'Risus pueri felicitas pura erat.', ARRAY['Gaudium', 'Laetitia'], ARRAY['Tristitia'], 'felicitas.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Ventus', 'Wind, the perceptible natural movement of the air.', 'VEN-toos', 'From Proto-Italic *wentos, from Proto-Indo-European *h₂wéntos (''wind'').', 'The wind swept across the plains.', 'Ventus per campos spiravit.', 'He felt the cool wind on his face.', 'Ventum frigidum in vultu sensit.', 'Trees bent under the strong wind.', 'Arbores sub vento valido inclinabantur.', ARRAY['Aura', 'Flatus'], ARRAY[]::TEXT[], 'ventus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Solis', 'Sun, the star at the center of the solar system.', 'SOH-lis', 'From Proto-Italic *sūlis, from Proto-Indo-European *sóh₂wl̥ (''sun'').', 'The sun warms the earth.', 'Sol terram calefacit.', 'He basked in the sun''s glow.', 'In splendore solis sese oblectavit.', 'The sun rises in the east.', 'Sol ab oriente oritur.', ARRAY['Phoebus', 'Titan'], ARRAY[]::TEXT[], 'solis.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Flos', 'Flower, the seed-bearing part of a plant.', 'FLOSS', 'From Proto-Italic *flōs, possibly from a Proto-Indo-European root related to ''bloom''.', 'The garden is full of vibrant flowers.', 'Hortus floribus vivis plenus est.', 'She picked a red flower.', 'Florem rubrum carpsit.', 'Flowers bloomed in the spring.', 'Flores vere floruerunt.', ARRAY['Floris', 'Flosculus'], ARRAY[]::TEXT[], 'flos.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Nox', 'Night, the period of darkness in each twenty-four hours.', 'NOHKS', 'From Proto-Italic *nokt-s, from Proto-Indo-European *nókʷts (''night'').', 'The stars shine brightly at night.', 'Stellae noctu lucent.', 'He dreams peacefully during the night.', 'Nocte tranquille somniat.', 'Owls hunt during the night.', 'Bubones nocte praedantur.', ARRAY['Tenebrae', 'Vesper'], ARRAY['Dies'], 'nox.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Fames', 'Hunger, a feeling of discomfort or weakness caused by lack of food.', 'FAH-mes', 'From Proto-Italic *famēs, from Proto-Indo-European *dʰeh₁-m- (''to suck, to drink'').', 'Hunger drives him to seek food.', 'Fames eum ad cibum quaerendum dirigit.', 'The famine left many in hunger.', 'Fames multos fame reliquit.', 'Hunger can overwhelm the mind.', 'Fames animum obruere potest.', ARRAY['Inedia', 'Fames'], ARRAY['Satietas'], 'fames.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Bellum', 'War, an armed conflict between different nations or states.', 'BEL-lum', 'From Proto-Italic *gʷelom, possibly from Proto-Indo-European *gʷelH- (to strike).', 'War devastates the land.', 'Bellum terram vastat.', 'The soldiers prepare for war.', 'Milites ad bellum se parant.', 'After the war, peace returns.', 'Post bellum, pax redit.', ARRAY['Pugna', 'Proelium'], ARRAY['Pax'], 'bellum.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Sapientia', 'Wisdom, the ability to think and act using knowledge, experience, understanding, and insight.', 'sa-pee-EN-tee-ah', 'Derived from the Latin ''sapiens,'' meaning ''wise'' or ''discerning.''', 'Wisdom is often gained through experience.', 'Sapientia saepe per experientiam acquiritur.', 'She showed great wisdom in her decision.', 'Magnam sapientiam in sua sententia ostendit.', 'Ancient philosophers taught the value of wisdom.', 'Philosophi antiqui sapientiae vim docuerunt.', ARRAY['Prudentia', 'Scientia'], ARRAY['Insipientia'], 'sapientia.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Aurum', 'Gold, a precious metal known for its luster and value.', 'OW-room', 'The word derives from the PIE root ''aus,'' meaning ''to shine.''', 'Gold is considered valuable across many cultures.', 'Aurum apud multas culturas pretiosum habetur.', 'She wore a necklace made of pure gold.', 'Monile ex puro auro factum gerebat.', 'The ancient coins were made of gold.', 'Nummi antiqui ex auro facti sunt.', ARRAY['Aurum'], ARRAY['Plumbum'], 'aurum.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Amicus', 'Friend, a person whom one knows and with whom one has a bond of mutual affection.', 'ah-MEE-koos', 'From Latin ''amo,'' meaning ''to love.''', 'A true friend is a treasure.', 'Verus amicus thesaurus est.', 'He trusted his friend''s advice.', 'Amici consilio credidit.', 'They went to the marketplace together.', 'In forum una ierunt.', ARRAY['Socius', 'Comes'], ARRAY['Hostis'], 'amicus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Libertas', 'Freedom, the power or right to act, speak, or think as one wants.', 'li-BER-tas', 'From the Latin ''liber,'' meaning ''free.''', 'Freedom is a fundamental human right.', 'Libertas ius humanum fundamentale est.', 'The citizens fought for their freedom.', 'Cives pro sua libertate pugnaverunt.', 'Freedom allows for personal and spiritual growth.', 'Libertas ad incrementum personalem et spiritualem permittit.', ARRAY['Libertatis', 'Independencia'], ARRAY['Servitus'], 'libertas.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Animus', 'Mind or soul, the spiritual or mental essence of a person.', 'AH-nee-moos', 'From Latin ''anima,'' meaning ''soul'' or ''spirit.''', 'The mind can be both a fortress and a prison.', 'Animus potest et arx et carcer esse.', 'She found strength in her mind''s resilience.', 'Fortitudine in animi constantia invenit.', 'The health of the soul influences the body.', 'Sanitas animi corpus afficit.', ARRAY['Mens', 'Spiritus'], ARRAY[]::TEXT[], 'animus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Vitium', 'Vice or fault, a moral failing or error.', 'WI-tee-um', 'Derived from the Latin term ‘vitare,’ meaning ‘to avoid.’', 'Greed can be considered a vice.', 'Avaritia vitium haberi potest.', 'Acknowledging one''s own faults is crucial for growth.', 'Suos vitia agnoscere ad incrementum necessarium est.', 'They sought to correct their faults.', 'Vitia sua corrigere temptaverunt.', ARRAY['Culpa', 'Error'], ARRAY['Virtus'], 'vitium.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Ignavia', 'Laziness or cowardice, a reluctance to act or lack of courage.', 'ig-NAH-wee-ah', 'From Latin ''ignavus,'' meaning ''idle'' or ''cowardly.''', 'Laziness can prevent success.', 'Ignavia successum impedire potest.', 'He faced his fears instead of succumbing to cowardice.', 'Metus suos potius quam ignaviae succubuit.', 'Their laziness led to missed opportunities.', 'Ignavia occasiones amissae duxit.', ARRAY['Acedia'], ARRAY['Industria', 'Fortitudo'], 'ignavia.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Vinum', 'Wine, an alcoholic drink made from fermented grapes.', 'VEE-noom', 'From the Latin ''vinum,'' possibly from a Proto-Italic or possibly Latin origination.', 'Wine has been enjoyed for centuries.', 'Vinum per saecula delectatum est.', 'They celebrated with a bottle of fine wine.', 'Cum poculo vini pretiosi celebraverunt.', 'The wine flowed freely at the banquet.', 'Vinum libere in convivio fluxit.', ARRAY['Caecubum', 'Falernum'], ARRAY[]::TEXT[], 'vinum.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Murus', 'Wall, a vertical structure used for enclosing an area.', 'MU-roos', 'Directly derived from Latin, potentially associated with the Greek ‘μαστός’ (mastós).', 'The wall protected the city from invaders.', 'Murus urbem ab hostibus defendit.', 'They climbed over the garden wall.', 'Trans murum hortum ascenderunt.', 'A mural was painted on the wall.', 'Murus pictura ornatus est.', ARRAY['Paries'], ARRAY[]::TEXT[], 'murus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Bellus', 'Pretty or charming, often used to describe people or things that are pleasing to the senses.', 'BEH-loos', 'From the diminutive of ''bonus,'' meaning good.', 'The flowers in the garden were exquisitely beautiful.', 'Flores in horto erant egregie belli.', 'She wore a lovely dress to the banquet.', 'Vestem bellam ad convivium gerebat.', 'His smile was both warm and charming.', 'Risus eius et calidus et bellus erat.', ARRAY['pulcher', 'venustus'], ARRAY[]::TEXT[], 'bellus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Aquila', 'An eagle; a large bird of prey known for its strength and keen sight.', 'AH-kwee-lah', 'Derived from the Latin word for eagle.', 'The eagle soared high above the hills.', 'Aquila super colles alte volavit.', 'In ancient Rome, the eagle symbolized power and authority.', 'In Roma antiqua, aquila potestatem auctoritatemque significabat.', 'With a sharp eye, the eagle hunted for its prey.', 'Acuto oculo, aquila praedam suam venabatur.', ARRAY['volucris', 'raptor'], ARRAY[]::TEXT[], 'aquila.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Carus', 'Dear or beloved; cherished by someone.', 'KAH-roos', 'From the Latin ''carus,'' meaning precious or dear.', 'She held her dear memories close to her heart.', 'Memorias caras ad pectus tenuit.', 'His dear friend visited him often.', 'Amicus carus eum saepe visitabat.', 'They exchanged many dear gifts over the years.', 'Multa dona cara post annos commutaverunt.', ARRAY['dilectus', 'amatus'], ARRAY['odio'], 'carus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Gloria', 'Glory or renown; great honor and admiration gained by achievements.', 'GLOH-ree-ah', 'From Latin ''gloria,'' meaning fame or admiration.', 'The warrior sought glory on the battlefield.', 'Gloriam in acie miles quaesivit.', 'Glory was depicted in his every deed.', 'Gloria in omnibus factis eius depicta est.', 'They celebrated the glory of their victorious leader.', 'Gloriam ducis victoriosi celebraverunt.', ARRAY['fama', 'laus'], ARRAY[]::TEXT[], 'gloria.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Fortis', 'Brave or strong; possessing courage.', 'FOR-tis', 'Derived from Latin ''fortis,'' meaning strong or powerful.', 'The strong knight faced the dragon without fear.', 'Miles fortis unam sine metu oppugnavit draconem.', 'His bravery in battles was renowned.', 'Fortitudo eius in proeliis clara erat.', 'Strength can be measured in many ways.', 'Fortia in multis modis metiri potest.', ARRAY['audax', 'validus'], ARRAY['ignavus'], 'fortis.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Mors', 'Death; the end of life or a cessation of being.', 'mōrs', 'From Proto-Indo-European ''mr̥tós,'' meaning dead or death.', 'Death comes to all living creatures.', 'Mors omnibus creaturis vivis venit.', 'He contemplated life and death with a heavy heart.', 'De vita et morte pectore ingravescente meditatus est.', 'In the stories, death was often depicted as a dark figure.', 'In fabulis, mors saepe ut imago obscura depicta est.', ARRAY['exitus', 'obitus'], ARRAY['vita'], 'mors.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Luxuria', 'Luxury; great comfort or extravagant living.', 'look-SOO-ree-ah', 'Derived from Latin ''luxus,'' meaning excess or extravagance.', 'They lived a life of luxury and splendor.', 'Vitam luxuriae et splendoris egerunt.', 'The banquet was a feast of luxury.', 'Conviviium luxuriosa epula erat.', 'Luxury was evident in every corner of the estate.', 'Luxuria in omni angulo fundi apparebat.', ARRAY['opulentia', 'splendor'], ARRAY['simplicitas'], 'luxuria.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Sapiens', 'Wise or discerning; possessing or showing intelligence and good judgment.', 'SAH-pee-ens', 'From Latin ''sapere,'' meaning to taste, to know.', 'He was known for his wise counsel.', 'Consiliis sapientibus notus erat.', 'In difficult times, the wise remain calm.', 'In temporibus difficilibus, sapientes tranquilli manent.', 'Her wisdom guided her through life''s challenges.', 'Sapientia eius per vitae difficultates duxit.', ARRAY['prudens', 'sagax'], ARRAY['stultus'], 'sapiens.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Natura', 'Nature; the inherent qualities or phenomena of the physical world.', 'nah-TOO-rah', 'From Latin ''natus,'' meaning born, referring to birth or origin.', 'She admired the wonders of nature.', 'Miracula naturae admirabatur.', 'Nature offers solace to those who seek it.', 'Natura solatium praebet petentibus.', 'The beauty of nature is unparalleled.', 'Pulchritudo naturae incomparabilis est.', ARRAY['universum', 'mundus'], ARRAY[]::TEXT[], 'natura.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Solus', 'Alone or solitary; being by oneself.', 'SOH-loos', 'From Proto-Indo-European ''swo,'' meaning one’s own.', 'He wandered the empty halls alone.', 'Per atria vacua solus ambulavit.', 'She enjoyed her solitary walks in the garden.', 'Ambulationes solitarias in horto amavit.', 'Being alone, he found peace.', 'Solus, pacem invenit.', ARRAY['singularis', 'unicus'], ARRAY['socius'], 'solus.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Celeritas', 'Speed or swiftness; the quality of being fast.', 'keh-LEH-ree-tas', 'Derived from the Latin ''celeris,'' meaning swift.', 'The athlete''s speed on the track was impressive.', 'Celeritas athletae in cursu memorabilis erat.', 'He moved with the swiftness of a cheetah.', 'Cum velocitate cephei se movebat.', 'Speed is crucial in a race.', 'Celeritas in cursu crucialis est.', ARRAY['velocitas', 'rapidity'], ARRAY['tarditas'], 'celeritas.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Fides', 'Faith or trust; confidence in someone or something.', 'FEE-days', 'From Latin ''fidere,'' meaning to trust.', 'Trust in others builds strong relationships.', 'Fides aliis relationes fortes confirmat.', 'He placed his faith in his comrades.', 'Fidem in sodales suos posuere.', 'Their faith never wavered, even in hard times.', 'Fides eorum numquam vacillavit, etiam temporibus duris.', ARRAY['confidentia', 'reliance'], ARRAY['credulus'], 'fides.jpg');
INSERT INTO word_of_the_day (word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES ('Labor', 'Work or toil; physical or mental exertion.', 'LAH-bor', 'From Latin ''labor,'' denoting toil or physical work.', 'Their hard work paid off with the harvest.', 'Labor durus cum messu frutus est.', 'Labor brings wealth and knowledge.', 'Labor opes et scientiam affert.', 'She labored tirelessly in the fields.', 'In agris indefatigabiliter laboravit.', ARRAY['opus', 'industria'], ARRAY['otium'], 'labor.jpg');

-- Verify row count
SELECT count(*) AS total_words FROM word_of_the_day;
