-- =============================================================
-- V3__add_generated_words.sql
-- Adds 12 words generated via the word generator tool.
-- =============================================================

INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (392, 'Ignorantia', 'Ignorantia means a lack of knowledge, understanding, or awareness about something.', 'iɡ-no-ran-ti-a', 'Derived from the Latin verb ''ignorare'', meaning ''to not know''.', 'Ignorance can often lead people to make uninformed decisions.', NULL, 'The scientist worked to dispel ignorance through education.', NULL, 'Ignorance of the law is not a valid excuse.', NULL, '{nescientia,inscientia}', '{scientia,cognitio}', 'ignorantia.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (393, 'Libri', 'Libri means books or written documents, typically bound and containing written or printed material.', 'li-bri', 'Comes from the Latin noun ''liber'', meaning ''book''.', 'The library was filled with old books on philosophy and history.', NULL, 'She spent her evening reading books by her favorite authors.', NULL, 'Books hold the key to unlocking new worlds and ideas.', NULL, '{volumina,codices}', '{}', 'libri.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (394, 'Auris', 'Auris means ear, the organ of hearing and balance in humans and other animals.', 'aw-ris', 'From Latin ''auris'', related to the Greek word ''ούς'' (ous) meaning ''ear''.', 'She whispered a secret into his ear.', NULL, 'The loud noise hurt his ears.', NULL, 'He listens carefully with his ears during the lecture.', NULL, '{auditio,auditus}', '{}', 'auris.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (395, 'Flamma', 'Flamma means flame, referring to the visible, gaseous part of a fire that emits light.', 'flam-ma', 'From the Latin root ''flamma'', which is akin to the Greek ''φλόξ'' (phlox), meaning flame or blaze.', 'The flame flickered in the breeze.', NULL, 'They sat by the campfire, watching the flames dance.', NULL, 'The flames consumed the dry wood quickly.', NULL, '{ardor,ignis}', '{gelum}', 'flamma.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (396, 'Avaritia', 'Avaritia means ''greed'' or ''avarice'' in Latin. It refers to an excessive or insatiable desire for wealth or material gain.', 'ah-vah-REE-tee-ah', 'Derived from the Latin adjective ''avarus'', meaning ''greedy''.', 'Greed can lead to one''s downfall.', NULL, 'The king''s avarice knew no bounds.', NULL, 'Avarice is one of the seven deadly sins.', NULL, '{Cupiditas,Rapacitas}', '{Liberalitas,Humilitas}', 'avaritia.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (397, 'Sitis', 'Sitis means thirst, the sensation of needing or wanting to drink water or another liquid.', 'SEE-tees', 'Derived from Latin ''sitio'', meaning ''to be thirsty''.', 'After a long run, Jane could feel the sitis overcoming her.', NULL, 'The travelers endured extreme sitis while crossing the desert.', NULL, 'His unbearable sitis led him to find water quickly.', NULL, '{Ardor,Sicitas}', '{}', 'sitis.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (398, 'Fructus', 'Fructus means fruit, the seed-bearing structure in flowering plants often consumed by humans and animals.', 'FROOK-toos', 'Comes from the Latin verb ''fruor'', meaning ''to enjoy''.', 'She enjoyed the fresh fructus from the market.', NULL, 'The tree was heavy with ripe fructus.', NULL, 'He picked a fructus from the orchard each morning.', NULL, '{Pomum,Bacca}', '{}', 'fructus.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (399, 'Caeruleus', 'Caeruleus means blue, a color resembling that of the clear sky or the deep sea.', 'kai-ROO-lay-us', 'Derived from ''caelum'', meaning ''sky'', indicating the blue color of a clear day.', 'The painter used caeruleus to depict the ocean in his artwork.', NULL, 'Caeruleus skies greeted the travelers as they reached the coast.', NULL, 'Her dress was a striking shade of caeruleus.', NULL, '{Azureus,Cyanus}', '{}', 'caeruleus.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (400, 'Flameum', 'Flameum means veil, particularly a bridal veil.', 'FLAH-may-oom', 'Derived from Latin ''flamma'', indicating the fiery or bright color traditionally associated with bridal veils.', 'The bride wore a beautiful flameum during the ceremony.', NULL, 'Her flameum trailed behind her as she walked down the aisle.', NULL, 'In ancient Rome, the flameum was a symbol of modesty and virtue.', NULL, '{Velum,Palla}', '{}', 'flameum.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (401, 'Felix', 'Felix means happy or fortunate, often referring to someone who is blessed with luck or good fortune.', 'FAY-leeks', 'From the Latin root meaning ''fruitful, blessed, happy''.', 'He considered himself felix to have such a supportive family.', NULL, 'Finding a rare coin in the garden made her day especially felix.', NULL, 'They had a felix reunion after years apart.', NULL, '{Laetus,Fortunatus}', '{Infelix}', 'felix.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (402, 'Amplitudo', 'Amplitudo means greatness or extent in terms of size, capacity, or degree.', 'am-pli-TOO-doh', 'Derived from the Latin ''amplus'' meaning large or spacious.', 'The amplitudo of the universe is a subject of fascination for scientists.', NULL, 'The architect was impressed by the amplitudo of the ancient structure.', NULL, 'They marveled at the amplitudo of the grand hall.', NULL, '{Magnitudo,Grandis}', '{}', 'amplitudo.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (403, 'Cedit', 'Cedit means to yield, go, or withdraw, often used in the context of moving aside or retreating.', 'ˈkeː.dit', 'From the Latin verb ''cedere'', meaning ''to go, move, withdraw, or yield''.', 'The army was forced to cede territory to the advancing forces.', NULL, 'As the river overflowed, the villagers decided to retreat to higher ground.', NULL, 'After a long debate, she decided to yield to the group''s decision.', NULL, '{Recipit,Recedit}', '{}', 'cedit.jpg');

-- Reset the sequence so future inserts get correct IDs
SELECT setval('word_of_the_day_id_seq', (SELECT MAX(id) FROM word_of_the_day));
