-- =============================================================
-- V4__add_generated_words_batch2.sql
-- Adds 20 words generated via the word generator tool (DALL-E 2).
-- =============================================================

INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (404, 'Glacies', 'Glacies means ice, the solid state of water that forms at low temperatures.', 'GLAH-kee-ays', 'From Proto-Italic *glakiās, from Proto-Indo-European *gel- (to freeze).', 'The lake was covered in a thick layer of ice.', NULL, 'Ice can be slippery and dangerous.', NULL, 'In winter, we often see ice forming on window panes.', NULL, '{Gelus,Pruna}', '{Ignis}', 'glacies.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (405, 'Puer', 'Puer means boy, referring to a male child or young man.', 'POO-er', 'From Proto-Italic *pouros, from Proto-Indo-European *ph₂wēr (child, offspring).', 'The boy plays in the park.', NULL, 'He is a curious boy, always asking questions.', NULL, 'The boy is learning to read and write.', NULL, '{Infans,Puerulus}', '{Puella}', 'puer.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (406, 'Fluvius', 'Fluvius means river, a large natural stream of water flowing to the sea, a lake, or another such stream.', 'FLU-vee-us', 'From Proto-Italic *flowyos, from Proto-Indo-European *plew- (to flow).', 'The river flows through the valley.', NULL, 'Many cities are located on the banks of a river.', NULL, 'The river is home to many species of fish.', NULL, '{Amnis,Rivus}', '{}', 'fluvius.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (407, 'Homines', 'Homines means people, referring to human beings collectively.', 'HOH-mee-nes', 'From Latin homo (man, human), plural form homines.', 'People need clean water to survive.', NULL, 'The city was bustling with people.', NULL, 'People of all ages attended the event.', NULL, '{Gens,Populus}', '{}', 'homines.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (408, 'Ludus', 'Ludus means game or play, referring to an activity for amusement or entertainment.', 'LOO-doos', 'From Proto-Italic *loudus, from Proto-Indo-European *leygʰ- (to jump).', 'They played a game of chess.', NULL, 'The children are outside playing games.', NULL, 'Board games are a popular pastime.', NULL, '{Jocus,Certamen}', '{Labor}', 'ludus.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (409, 'Agricola', 'Agricola means farmer, a person engaged in agriculture, raising living organisms for food or raw materials.', 'a-GREE-ko-la', 'From ager (field) + colō (cultivate), literally ''cultivator of fields''.', 'The farmer plowed his fields in spring.', NULL, 'Farmers work hard to produce food.', NULL, 'She inherited the farm from her father, a devoted farmer.', NULL, '{Rusticus,Colonus}', '{}', 'agricola.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (410, 'Nomen', 'Nomen means name, a word or set of words by which a person or thing is known, addressed, or referred to.', 'NOH-men', 'From Proto-Italic *nōmn, from Proto-Indo-European *h₁nómn̥.', 'Her name is Julia.', NULL, 'Names can hold significant meaning.', NULL, 'They wrote their names on the list.', NULL, '{Appellatio,Titulus}', '{}', 'nomen.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (411, 'Somnium', 'Somnium means dream, a series of thoughts, images, and sensations occurring in a person''s mind during sleep.', 'SOM-nee-um', 'From somnus (sleep) + -ium (noun suffix).', 'She recounted her strange dream to her friends.', NULL, 'Dreams can sometimes be difficult to interpret.', NULL, 'He had a recurring dream about flying.', NULL, '{Visio,Insomnia}', '{}', 'somnium.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (412, 'Arma', 'Arma means arms, referring to weapons and equipment used in combat or warfare.', 'AR-ma', 'From Proto-Italic *armaz, from Proto-Indo-European *h₂er-mo- (fitting, tool, tool of offensive).', 'The soldiers were equipped with arms.', NULL, 'He collected antique arms and armor.', NULL, 'The display included arms from different historical periods.', NULL, '{Tela,Militia}', '{}', 'arma.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (413, 'Sanguinarius', 'Sanguinarius means bloodthirsty or eager for bloodshed and violence.', 'san-gwee-NAH-ree-oos', 'Derived from Latin ''sanguis'' meaning blood.', 'The gladiator was known for his sanguinary tendencies in the arena.', NULL, 'The warlord''s sanguinary nature made him a fearsome leader.', NULL, 'The novel depicted a world of sanguinary battles and endless violence.', NULL, '{cruentus,atrox}', '{mitis}', 'sanguinarius.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (414, 'Sagacitas', 'Sagacitas means keenness of perception or wisdom.', 'sa-ga-KEE-taas', 'From Latin ''sagax'' meaning wise or shrewd.', 'Her sagacity was evident in the way she solved complex problems.', NULL, 'The sage was respected for his sagacity.', NULL, 'Sagacity can lead one to make sound decisions.', NULL, '{prudentia,sapientia}', '{}', 'sagacitas.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (415, 'Veneficus', 'Veneficus means a sorcerer or poisoner.', 'weh-NEH-fee-koos', 'From Latin ''venenum'' meaning poison and ''facere'' meaning to make.', 'The veneficus was feared in the village for his dark arts.', NULL, 'Legends spoke of a veneficus who could brew deadly potions.', NULL, 'The veneficus was captured and tried for treason against the king.', NULL, '{magus,venator}', '{}', 'veneficus.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (416, 'Vulpes', 'Vulpes means a fox, often symbolizing cunning or trickiness.', 'WUL-pehs', 'Derived directly from the Latin ''vulpes''.', 'The vulpes slyly evaded all the traps set by the hunters.', NULL, 'In fables, the vulpes is often portrayed as a clever character.', NULL, 'The farmers were always wary of the vulpes near their farms.', NULL, '{catus,subdolus}', '{}', 'vulpes.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (417, 'Zelus', 'Zelus means an enthusiastic devotion or eagerness.', 'ZEH-loos', 'Derived from Greek ''zelos'', meaning zeal.', 'Her zelus for learning was evident in her academic success.', NULL, 'The young knight''s zelus drove him to prove his valor.', NULL, 'Zelus in a team can inspire great achievements.', NULL, '{studium,fervor}', '{}', 'zelus.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (418, 'Xiphias', 'Xiphias refers to a swordfish, known for its elongated, sword-like bill.', 'KSIP-ee-ahs', 'From Greek ''xiphos'' meaning sword.', 'The xiphias was a prized catch for the fishermen.', NULL, 'Observing the xiphias in its natural habitat was mesmerizing.', NULL, 'The swift movements of the xiphias make it a formidable predator.', NULL, '{gladius piscis,ensis piscis}', '{}', 'xiphias.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (419, 'Lacrima', 'Lacrima means a tear, as in a drop of liquid that flows from the eye.', 'LAH-kree-mah', 'Derived from the Latin ''lacrima'', related to the act of weeping.', 'A single lacrima fell as she heard the tragic news.', NULL, 'The painting captured a lacrima at the edge of the child''s eyelash.', NULL, 'The letter was stained with lacrimae of sorrow.', NULL, '{fletus,lacrimation}', '{}', 'lacrima.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (420, 'Navita', 'Navita means a sailor or mariner, one who navigates the seas.', 'NAH-wi-tah', 'From Latin ''navis'' meaning ship.', 'The navita set sail at dawn, seeking new adventures.', NULL, 'Life as a navita requires resilience and courage.', NULL, 'The seasoned navita shared tales of distant lands.', NULL, '{nauta,marinus}', '{}', 'navita.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (421, 'Ignipotens', 'Ignipotens means powerful in fire or mastering fire.', 'ig-nee-POH-tens', 'From Latin ''ignis'' meaning fire and ''potens'' meaning powerful.', 'The blacksmith, known for his ignipotens skills, was the best in the village.', NULL, 'Myths spoke of a deity who was ignipotens, commanding the flames.', NULL, 'He was drawn to the forge, aspiring to become ignipotens.', NULL, '{ignifluus,flammarum dominus}', '{}', 'ignipotens.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (422, 'Lignarius', 'Lignarius means related to wood or a worker in woodcraft.', 'lig-NAH-ree-oos', 'From Latin ''lignum'' meaning wood.', 'The lignarius crafted beautiful furniture from oak.', NULL, 'As a lignarius, he had a keen eye for quality timber.', NULL, 'His lignarius skills were in high demand in the growing town.', NULL, '{faber lignarius,faber}', '{}', 'lignarius.jpg');
INSERT INTO word_of_the_day (id, word, definition, pronunciation, origin, example0, example0_latin, example1, example1_latin, example2, example2_latin, synonyms, antonyms, image) VALUES (423, 'Opulentia', 'Opulentia means wealth or abundance, especially in a luxurious sense.', 'oh-poo-LEN-tee-ah', 'From Latin ''opulentus'' meaning wealthy.', 'The opulentia of the palace was unmatched in the entire kingdom.', NULL, 'His opulentia allowed him to live a life of great comfort and ease.', NULL, 'The festival was a display of opulentia and celebration.', NULL, '{divitiae,luxuria}', '{}', 'opulentia.jpg');

-- Reset the sequence so future inserts get correct IDs
SELECT setval('word_of_the_day_id_seq', (SELECT MAX(id) FROM word_of_the_day));
